/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProvidersProviderIDRouteImport } from './routes/providers.$providerID'
import { Route as ProvidersProviderIDIndexRouteImport } from './routes/providers.$providerID.index'
import { Route as ProvidersProviderIDSuccessRouteImport } from './routes/providers.$providerID.success'
import { Route as ProvidersProviderIDMethodsMethodIDRouteImport } from './routes/providers.$providerID.methods.$methodID'

const ProvidersProviderIDRoute = ProvidersProviderIDRouteImport.update({
  id: '/providers/$providerID',
  path: '/providers/$providerID',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersProviderIDIndexRoute =
  ProvidersProviderIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProvidersProviderIDRoute,
  } as any)
const ProvidersProviderIDSuccessRoute =
  ProvidersProviderIDSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => ProvidersProviderIDRoute,
  } as any)
const ProvidersProviderIDMethodsMethodIDRoute =
  ProvidersProviderIDMethodsMethodIDRouteImport.update({
    id: '/methods/$methodID',
    path: '/methods/$methodID',
    getParentRoute: () => ProvidersProviderIDRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/providers/$providerID': typeof ProvidersProviderIDRouteWithChildren
  '/providers/$providerID/success': typeof ProvidersProviderIDSuccessRoute
  '/providers/$providerID/': typeof ProvidersProviderIDIndexRoute
  '/providers/$providerID/methods/$methodID': typeof ProvidersProviderIDMethodsMethodIDRoute
}
export interface FileRoutesByTo {
  '/providers/$providerID/success': typeof ProvidersProviderIDSuccessRoute
  '/providers/$providerID': typeof ProvidersProviderIDIndexRoute
  '/providers/$providerID/methods/$methodID': typeof ProvidersProviderIDMethodsMethodIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/providers/$providerID': typeof ProvidersProviderIDRouteWithChildren
  '/providers/$providerID/success': typeof ProvidersProviderIDSuccessRoute
  '/providers/$providerID/': typeof ProvidersProviderIDIndexRoute
  '/providers/$providerID/methods/$methodID': typeof ProvidersProviderIDMethodsMethodIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/providers/$providerID'
    | '/providers/$providerID/success'
    | '/providers/$providerID/'
    | '/providers/$providerID/methods/$methodID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/providers/$providerID/success'
    | '/providers/$providerID'
    | '/providers/$providerID/methods/$methodID'
  id:
    | '__root__'
    | '/providers/$providerID'
    | '/providers/$providerID/success'
    | '/providers/$providerID/'
    | '/providers/$providerID/methods/$methodID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProvidersProviderIDRoute: typeof ProvidersProviderIDRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/providers/$providerID': {
      id: '/providers/$providerID'
      path: '/providers/$providerID'
      fullPath: '/providers/$providerID'
      preLoaderRoute: typeof ProvidersProviderIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$providerID/': {
      id: '/providers/$providerID/'
      path: '/'
      fullPath: '/providers/$providerID/'
      preLoaderRoute: typeof ProvidersProviderIDIndexRouteImport
      parentRoute: typeof ProvidersProviderIDRoute
    }
    '/providers/$providerID/success': {
      id: '/providers/$providerID/success'
      path: '/success'
      fullPath: '/providers/$providerID/success'
      preLoaderRoute: typeof ProvidersProviderIDSuccessRouteImport
      parentRoute: typeof ProvidersProviderIDRoute
    }
    '/providers/$providerID/methods/$methodID': {
      id: '/providers/$providerID/methods/$methodID'
      path: '/methods/$methodID'
      fullPath: '/providers/$providerID/methods/$methodID'
      preLoaderRoute: typeof ProvidersProviderIDMethodsMethodIDRouteImport
      parentRoute: typeof ProvidersProviderIDRoute
    }
  }
}

interface ProvidersProviderIDRouteChildren {
  ProvidersProviderIDSuccessRoute: typeof ProvidersProviderIDSuccessRoute
  ProvidersProviderIDIndexRoute: typeof ProvidersProviderIDIndexRoute
  ProvidersProviderIDMethodsMethodIDRoute: typeof ProvidersProviderIDMethodsMethodIDRoute
}

const ProvidersProviderIDRouteChildren: ProvidersProviderIDRouteChildren = {
  ProvidersProviderIDSuccessRoute: ProvidersProviderIDSuccessRoute,
  ProvidersProviderIDIndexRoute: ProvidersProviderIDIndexRoute,
  ProvidersProviderIDMethodsMethodIDRoute:
    ProvidersProviderIDMethodsMethodIDRoute,
}

const ProvidersProviderIDRouteWithChildren =
  ProvidersProviderIDRoute._addFileChildren(ProvidersProviderIDRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProvidersProviderIDRoute: ProvidersProviderIDRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
